# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20170802_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
