# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_auto_20170807_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
