# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_auto_20170807_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
